NewsManagement.AdminApp/Controllers/Components/NavMainViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewsManagement.AdminApp.Controllers.Components
{
    public class NavMainViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("Default"));
        }
    }
}

NewsManagement.AdminApp/Controllers/Components/NavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewsManagement.AdminApp.Controllers.Components
{
    public class NavigationViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("Default"));
        }

    }
}

NewsManagement.AdminApp/Controllers/Components/PagerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NewsManagement.ApiIntegration;
using NewsManagement.ViewModels.Common;
using System.Threading.Tasks;

namespace NewsManagement.AdminApp.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        private readonly ICategoryApiClient _categoryApiClient;

        public PagerViewComponent(ICategoryApiClient categoryApiClient)
        {

            _categoryApiClient = categoryApiClient;
        }
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

NewsManagement.AdminApp/Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using NewsManagement.ApiIntegration;
using NewsManagement.ViewModels.Catalog.Newss;
using System.Net;
using System.Threading.Tasks;

namespace NewsManagement.AdminApp.Controllers
{
    public class NewsController : BaseController
    {
        private readonly INewsApiClient _newsApiClient;
        private readonly IConfiguration _configuration;

        private readonly IEventApiClient _eventApiClient;
        private readonly ITopicApiClient _topicApiClient;
        private readonly ICityApiClient _cityApiClient;
       

        public NewsController(INewsApiClient newsApiClient,
            IConfiguration configuration, 
            IEventApiClient eventApiClient,
            ITopicApiClient topicApiClient,
            ICityApiClient cityApiClient
            )
        {
            _newsApiClient = newsApiClient;
            _configuration = configuration;
            _eventApiClient = eventApiClient;
            _topicApiClient = topicApiClient;
            _cityApiClient = cityApiClient;
        }
        public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 10)
        {
            var username = User.Identity.Name;
            var request = new GetManageNewsPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize,
                UserName = username
            };
            var data = await _newsApiClient.GetAllPaging(request);
            ViewBag.Keyword = keyword;
            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Topics = await _topicApiClient.GetAll(0);
            ViewBag.Events = await _eventApiClient.GetAll(0);
            ViewBag.Cities = await _cityApiClient.GetAll(0);
            return View();
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Create([FromForm]NewsCreateRequest request)
        {
            ViewBag.Topics = await _topicApiClient.GetAll(request.TopicId );
            ViewBag.Events = await _eventApiClient.GetAll(request.EventId );
            ViewBag.Cities = await _cityApiClient.GetAll(request.CityId );
            if (!ModelState.IsValid)
                return View();

            var result = await _newsApiClient.Create(request);

            if (result)
            {
                TempData["AlertMessage"] = "Thêm mới tin tức thành công";
                TempData["AlertType"] = "alert-success";
                return RedirectToAction("Index");
            }
            TempData["AlertMessage"] = "Thêm mới tin tức bị lỗi";
            TempData["AlertType"] = "alert-warning";
            return View(request);
        }
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var result = await _newsApiClient.GetById(id);
            if (result != null)
            {
                
                ViewBag.Topics = await _topicApiClient.GetAll(result.TopicId);
                ViewBag.Events = await _eventApiClient.GetAll(result.EventId);
                ViewBag.Cities = await _cityApiClient.GetAll(result.CityId);
                var updateRequest = new NewsUpdateRequest()
                {
                    Title = result.Title,
                    Description = result.Description,
                    Content = result.Content,
                    Img = result.Img,
                    Video = result.Video,
                    News_Hot = result.News_Hot,
                    Keyword = result.Keyword,
                    CityId = result.CityId,
                    EventId = result.EventId,
                    TopicId = result.TopicId,
                    Status = result.Status
                };
                return View(updateRequest);
            }
            return RedirectToAction("Error", "Home");
        }
        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Update([FromForm] NewsUpdateRequest request)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }
            ViewBag.Topics = await _topicApiClient.GetAll(request.TopicId);
            ViewBag.Events = await _eventApiClient.GetAll(request.EventId);
            ViewBag.Cities = await _cityApiClient.GetAll(request.CityId);

            var result = await _newsApiClient.Update(request);
            if (result)
            {
                TempData["AlertMessage"] = "Thay đổi thông tin tin tức thành công";
                TempData["AlertType"] = "alert-success";
                return RedirectToAction("Index");
            }
            TempData["AlertMessage"] = "Thay đổi thông tin tin tức bị lỗi";
            TempData["AlertType"] = "alert-warning";
            return View(request);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int Id)
        {
            var result = await _newsApiClient.Delete(Id);
            return Json(new { response = result });
        }
    }
}

NewsManagement.AdminApp/Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using NewsManagement.ApiIntegration;
using NewsManagement.Data.Enums;
using NewsManagement.ViewModels.System.Users;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewsManagement.AdminApp.Controllers
{
    public class UserController : BaseController
    {
        private readonly IUserApiClient _userApiClient;
        private readonly IConfiguration _configuration;
        /* private readonly IRoleApiClient _roleApiClient;*/

        public UserController(IUserApiClient userApiClient,
            /*IRoleApiClient roleApiClient,*/
            IConfiguration configuration)
        {
            _userApiClient = userApiClient;
            _configuration = configuration;
            /*_roleApiClient = roleApiClient;*/
        }

        public async Task<IActionResult> Index(string keyword, string rolename, int pageIndex = 1, int pageSize = 10)
        {
             if(ViewBag.Role != null)
            {
                var role = ViewBag.Role;
            }
            List<SelectListItem> selectListItems = new List<SelectListItem>()
            {
                new SelectListItem(text: "Khách Hàng", value: "client"),
                new SelectListItem(text: "Người dùng", value: "user")
            };
            if (User.IsInRole("admin"))
            {
                selectListItems.Add(new SelectListItem(text: "Tất cả", value: "all"));
                selectListItems.Add(new SelectListItem(text: "Nhân viên", value: "staff"));
            }
            else
            {
                if (rolename == null)
                {
                    rolename = "user";
                }
            }
            ViewBag.rolename = selectListItems.Select(x => new SelectListItem()
            {
                Text = x.Text,
                Value = x.Value,
                Selected = rolename == x.Value
            }); 

            var request = new GetUserPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize,
                RoleName = rolename
            };
            var data = await _userApiClient.GetUsersPagings(request);
            ViewBag.Keyword = keyword;
            if(rolename != null)
                ViewBag.Role = rolename;
            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            return View(data.ResultObj);
        }


        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var result = await _userApiClient.GetById(id);
            return View(result.ResultObj);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Create([FromForm] ManageRegisterRequest request)
        {
            if (!ModelState.IsValid)
                return View();
            request.NameRole = "staff";
            var result = await _userApiClient.RegisterUser(request);

            if (result.IsSuccessed)
            {
                TempData["AlertMessage"] = "Thêm mới người dùng thành công";
                TempData["AlertType"] = "alert-success";
                return RedirectToAction("Index");
            }



            ModelState.AddModelError("", result.Message);
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var result = await _userApiClient.GetById(id);
            if (result.IsSuccessed)
            {
                var user = result.ResultObj;
                var updateRequest = new UserUpdateRequest()
                {
                    Dob = user.Dob,
                    Email = user.Email,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    PhoneNumber = user.PhoneNumber,
                    Id = id,
                    Address = user.Address,
                    Status = user.Status == Status.Active ? true : false,
                    img = user.Img
                };
                return View(updateRequest);
            }
            return RedirectToAction("Error", "Home");
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Update([FromForm] UserUpdateRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _userApiClient.UpdateUser(request.Id, request);
            if (result.IsSuccessed)
            {
                TempData["AlertMessage"] = "Thay đổi thông tin người dùng thành công";
                TempData["AlertType"] = "alert-success";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> Detailt(Guid id)
        {
            var result = await _userApiClient.GetById(id);
            if (result.IsSuccessed)
            {
                var user = result.ResultObj;
                var updateRequest = new UserVm()
                {
                    Dob = user.Dob,
                    Email = user.Email,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    PhoneNumber = user.PhoneNumber,
                    Id = id,
                    Address = user.Address,
                    Img = user.Img,
                    UserName = user.UserName,
                    Status = user.Status //== Status.Active ? true : false
                };
                return View(updateRequest);
            }
            return RedirectToAction("Error", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid idUser )
        {
            var result = await _userApiClient.Delete(idUser);
            return Json(new { response = result });
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("Token");
            return RedirectToAction("Index", "Login");
        }
    }
}

NewsManagement.AdminApp/Views/Shared/Components/Navigation/Default.cshtml
    <ul class="navbar-nav  justify-content-end">
        <li class="nav-item d-flex align-items-center dropdown pe-2">
            <a href="javascript:;" class="nav-link text-body font-weight-bold px-0" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa fa-user me-sm-1"></i>
                <span class="d-sm-inline d-none ms-1">

                    @User.Identity.Name
                </span>


            </a>
            <ul class="dropdown-menu dropdown-menu-end px-2 py-3 me-sm-n4" aria-labelledby="dropdownMenuButton">

                <li class="mb-2">
                    <a class="dropdown-item border-radius-md" href="@Url.Action("Index", "News", new { id = "" })">

                        <div class="d-flex py-1">
                            <div class="my-auto">
                                <span class="avatar avatar-sm  me-3 " style="color: #344767; font-size:2rem;">
                                    <i class='bx bx-user bx-flip-horizontal'></i>
                                </span>
                            </div>
                            <div class="d-flex flex-column justify-content-center">
                                <h6 class="text-sm font-weight-normal mb-1">
                                    <span class="font-weight-bold">Thông tin cá nhân</span>
                                </h6>

                            </div>
                        </div>
                    </a>
                </li>


                <li class="mb-2">
                    <form method="post" asp-controller="User" asp-action="Logout">
                        <div class="dropdown-item border-radius-md">
                            <div class="d-flex py-1">
                                <div class="my-auto">
                                    @* <img src="../../assets/img/team-2.jpg" class="avatar avatar-sm  me-3 " alt="user image">*@
                                    <span class="avatar avatar-sm  me-3 " style="color: #344767; font-size:2rem;">
                                        <i class='bx bx-log-out-circle bx-rotate-180 '></i>
                                    </span>
                                </div>
                                <div class="d-flex flex-column justify-content-center">
                                    <h6 class="text-sm font-weight-normal mb-1">
                                        <button type="submit" class="dropdown-item">  <span class="font-weight-bold">Đăng xuất</span></button>
                                    </h6>
                                </div>
                            </div>
                        </div>
                    </form>
                </li>
            </ul>
        </li>
        <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
            <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
                <div class="sidenav-toggler-inner">
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                </div>
            </a>
        </li>
        <li class="nav-item px-3 d-flex align-items-center">
            <a href="javascript:;" class="nav-link text-body p-0">
                <i class="fa fa-cog fixed-plugin-button-nav cursor-pointer"></i>
            </a>
        </li>
        <li class="nav-item dropdown pe-2 d-flex align-items-center">
            <a href="javascript:;" class="nav-link text-body p-0" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa fa-bell cursor-pointer"></i>
            </a>
            <ul class="dropdown-menu dropdown-menu-end px-2 py-3 me-sm-n4" aria-labelledby="dropdownMenuButton">
                <li class="mb-2">
                    <a class="dropdown-item border-radius-md" href="javascript:;">
                        <div class="d-flex py-1">
                            <div class="my-auto">
                                <img src="../../assets/img/team-2.jpg" class="avatar avatar-sm  me-3 " alt="user image">
                            </div>
                            <div class="d-flex flex-column justify-content-center">
                                <h6 class="text-sm font-weight-normal mb-1">
                                    <span class="font-weight-bold">New message</span> from Laur
                                </h6>
                                <p class="text-xs text-secondary mb-0">
                                    <i class="fa fa-clock me-1"></i>
                                    13 minutes ago
                                </p>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="mb-2">
                    <a class="dropdown-item border-radius-md" href="javascript:;">
                        <div class="d-flex py-1">
                            <div class="my-auto">
                                <img src="../../assets/img/small-logos/logo-spotify.svg" class="avatar avatar-sm bg-gradient-dark  me-3 " alt="logo spotify">
                            </div>
                            <div class="d-flex flex-column justify-content-center">
                                <h6 class="text-sm font-weight-normal mb-1">
                                    <span class="font-weight-bold">New album</span> by Travis Scott
                                </h6>
                                <p class="text-xs text-secondary mb-0">
                                    <i class="fa fa-clock me-1"></i>
                                    1 day
                                </p>
                            </div>
                        </div>
                    </a>
                </li>
                <li>
                    <a class="dropdown-item border-radius-md" href="javascript:;">
                        <div class="d-flex py-1">
                            <div class="avatar avatar-sm bg-gradient-secondary  me-3  my-auto">
                                <svg width="12px" height="12px" viewBox="0 0 43 36" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                                    <title>credit-card</title>
                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <g transform="translate(-2169.000000, -745.000000)" fill="#FFFFFF" fill-rule="nonzero">
                                            <g transform="translate(1716.000000, 291.000000)">
                                                <g transform="translate(453.000000, 454.000000)">
                                                    <path class="color-background" d="M43,10.7482083 L43,3.58333333 C43,1.60354167 41.3964583,0 39.4166667,0 L3.58333333,0 C1.60354167,0 0,1.60354167 0,3.58333333 L0,10.7482083 L43,10.7482083 Z" opacity="0.593633743"></path>
                                                    <path class="color-background" d="M0,16.125 L0,32.25 C0,34.2297917 1.60354167,35.8333333 3.58333333,35.8333333 L39.4166667,35.8333333 C41.3964583,35.8333333 43,34.2297917 43,32.25 L43,16.125 L0,16.125 Z M19.7083333,26.875 L7.16666667,26.875 L7.16666667,23.2916667 L19.7083333,23.2916667 L19.7083333,26.875 Z M35.8333333,26.875 L28.6666667,26.875 L28.6666667,23.2916667 L35.8333333,23.2916667 L35.8333333,26.875 Z"></path>
                                                </g>
                                            </g>
                                        </g>
                                    </g>
                                </svg>
                            </div>
                            <div class="d-flex flex-column justify-content-center">
                                <h6 class="text-sm font-weight-normal mb-1">
                                    Payment successfully completed
                                </h6>
                                <p class="text-xs text-secondary mb-0">
                                    <i class="fa fa-clock me-1"></i>
                                    2 days
                                </p>
                            </div>
                        </div>
                    </a>
                </li>
            </ul>
        </li>
    </ul>